### ISSUE TITLE
register new user failed

### ISSUE THREAD

**Issue by rsedlmeier** [matthiasstraka/php-invest#27]
Looks like a simple db/sql error, here's the apache2 log

[Fri Apr 14 02:52:54.995296 2023] [php:notice] [pid 17393] [client 192.168.2.107:49216] [critical] Uncaught PHP Exception Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException: "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'currency' cannot be null" at /cloud/invest/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 114, referer: http://192.168.2.222/invest/register

**Comment by matthiasstraka** [comment]
Thanks, haven't used that code path in a while. I'll look into it.
